# Generated by Django 3.1.7 on 2021-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0002_auto_20210723_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertmodel',
            name='test',
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='length',
            field=models.IntegerField(verbose_name='مدت زمان'),
        ),
    ]
