# Generated by Django 3.1.7 on 2021-07-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0003_auto_20210723_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertmodel',
            name='length',
            field=models.IntegerField(default=200, verbose_name='مدت زمان'),
        ),
    ]
