# Generated by Django 3.1.7 on 2021-07-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketSales', '0005_auto_20210727_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertmodel',
            name='Poster',
            field=models.ImageField(null=True, upload_to='concertImages/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='concertmodel',
            name='length',
            field=models.IntegerField(verbose_name='مدت زمان'),
        ),
    ]
